class Transaction {
  final String id;
  final String customerId;
  final double amount;
  final String type; // 'debt' or 'payment'
  final DateTime date;
  final String? note;

  Transaction({
    required this.id,
    required this.customerId,
    required this.amount,
    required this.type,
    required this.date,
    this.note,
  });

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // ID is usually generated by server or passed if needed
      'customer_id': customerId,
      'amount': amount,
      'type': type,
      'date': date.toIso8601String(),
      'note': note,
    };
  }

  factory Transaction.fromJson(Map<String, dynamic> json) {
    return Transaction(
      id: json['id'],
      customerId: json['customer_id'],
      amount: (json['amount'] as num).toDouble(),
      type: json['type'],
      date: DateTime.parse(json['date']),
      note: json['note'],
    );
  }
}

class Customer {
  final String id;
  final String name;
  final String phone;
  final String address;
  double totalDebt;
  DateTime lastTransactionDate;

  Customer({
    required this.id,
    required this.name,
    this.phone = '',
    this.address = '',
    this.totalDebt = 0.0,
    required this.lastTransactionDate,
  });

  Map<String, dynamic> toJson() {
    return {
      // 'id': id,
      'name': name,
      'phone': phone,
      'address': address,
      'total_debt': totalDebt,
      'last_transaction_date': lastTransactionDate.toIso8601String(),
    };
  }

  factory Customer.fromJson(Map<String, dynamic> json) {
    return Customer(
      id: json['id'],
      name: json['name'],
      phone: json['phone'],
      address: json['address'],
      totalDebt: (json['total_debt'] as num?)?.toDouble() ?? 0.0,
      lastTransactionDate: json['last_transaction_date'] != null
          ? DateTime.parse(json['last_transaction_date'])
          : DateTime.now(), // Fallback or handle nullable
    );
  }
}
